
<link rel="stylesheet" href="guest.css" />

<body>
  <div class="container">
    <div class="row">

      <div class="col-md-12">
        <h1 class="page-header" id="userStat">Guest</h1>


        <div class="btn-group">
         <button type="button" class="btn btn-default" id="Join" onClick="location.href = 'Join.html'">Join</button>
          <button type="button" class="btn btn-default" id="Login" onClick="location.href = 'login.html'">Login</button>
        </div>
      </div>

      <div class="col-md-6 col-md-offset-3 hide">
        <div class="alert alert-info alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-2">

        <h2 class="h3 profile">Profile/Config</h2>
        <h3 class="h4 userid">User Id</h3>

        <form class="form-inline">
          <div class="form-group">
            <label for="userId" class="sr-only">User Id</label>
            <input type="text" class="form-control" id="userId" placeholder="Enter your user email." value="">
          </div>
      </form>

        <h2 class="h3">Channel</h2>
        <form> <!-- action="controltOwnerView.php" method="post" -->
          <div class="from-gruop">
            <input class="form-control" type="text" id="createChannelId" placeholder="Create and connect the channel." value="" readonly="">
            <label class="sr-only" for="createChannelId">Channel Id</label>
          </div>
          <button class="btn btn-default btn-sm btn-block" id="createChannel">
            <span class="glyphicon glyphicon-phone-alt" aria-hidden="true"></span> Create
          </button>
        </form>
        <button class="btn btn-default btn-sm btn-block" id="disconnectChannel">
          <span class="glyphicon glyphicon-stop" aria-hidden="true"></span> Disconnect
        </button>

         <h3 class="h4 Connecth3">Connect</h3>
         <button class="btn btn-default btn-sm" id="refreshChannel">
          <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span> Refresh
        </button>
         <div class="list-group channel-list" id="channelList"></div>
       </div>

        <div class="chat-timeline" id="timeline"></div>

        <form>
          <label class="sr-only" for="sendMessage">Transfer Message</label>
          <div class="input-group input-group-sm">
            <div class="input-group-addon">
              <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            </div>
            <input type="text" class="form-control" id="sendMessage" placeholder="Enter your message.">
            <span class="input-group-btn">
              <button class="btn btn-default" id="sendText">
                <span class="glyphicon glyphicon-send" aria-hidden="true"></span> Send
              </button>
            </span>
          </div>
        </form>

        <div class="col-md-7 videoArea">
          <h2 class="h3">Remote</h2>
          <div class="well">
            <video class="remote-video center-block" id="remoteVideo"></video>
          </div>
        </div>

        <div class="col-md-3 videoArea">
          <h2 class="h3">Local</h2>
          <div class="well">
            <video class="local-video center-block" id="localVideo" muted></video>
          </div>
        </div>

    </div>
  </div>

  <script src="//code.jquery.com/jquery-2.1.3.min.js"></script>
  <!-- <script src="http://ajax.googleapis.com/ajax/libs/prototype/1.7.1.0/prototype.js" type="text/javascript"></script> -->
  <script src="//www.playrtc.com/sdk/js/playrtc.js"></script>
  <script src="GuestJS.js"></script>