<?php echo $this->getContent(); ?>

<footer>

	<div class='footer-limiter'>
		<div class="footer-left">

			<h3>Inter<span>phone</span></h3>

			<p class="footer-links">
				<a href="/">Home</a>
				·
				<a href="/About">About</a>
			</p>

			<p class="footer-company-name">Company Name &copy; 2015</p>
		</div>

		<div class="footer-center">

			<div>
				<i class="fa fa-map-marker"></i>
				<p><span>경기도 안산시 상록구 한양대학로 55</span> Ansan, Korea</p>
			</div>

			<div>
				<i class="fa fa-phone"></i>
				<p><a href="tel:01033955249">010 3395 5249</a></p>
			</div>

			<div>
				<i class="fa fa-envelope"></i>
				<p><a href="mailto:grandmorning@hotmail.com">grandmorning@hotmail.com</a></p>
			</div>

		</div>

		<div class="footer-right">

			<p class="footer-company-about">
				<span>실버타운</span>
				“다들 놀라지. 그 나이에 학교 다녀서 뭐하냐고.” 처음에는 주변 학생들을 거북하게 만드는 것은 아닐지, 학과 공부를 따라갈 수는 있을지 걱정이 많았다고 한다. 그러나 27이 넘은 나이들에도 배움의 끈을 놓지 않고 마침내 우리는 실버타운을 이루고 Web-rtc 인터폰 서비스를 오픈한다.
			</p>

		</div>
	</div>

</footer>