<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h2 class="h3">Host</h2>
			<input class="form-control" type="hidden" id="connectChannelId" value="<?= $channelId ?>">

			<div class="col-md-10">
				<div id="loading-container" class='col-md-12'>
					<div class="stick"></div>
					<div class="stick"></div>
					<div class="stick"></div>
					<div class="stick"></div>
					<div class="stick"></div>
					<div class="stick"></div>

					<p id='loading-text'>연결중입니다...</p>
				</div>
			</div>
			<video class="remote-video center-block col-md-12" id="calleeRemoteVideo"></video>
		</div>
	</div>
</div>