<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h2 class="h3">Callee</h2>
      <h3 class="h4">Connect Channel</h3>
      <form class="form-inline">
        <div class="form-group">
          <label class="sr-only" for="connectChannelId">Channel Id</label>
          <input class="form-control" type="text" id="connectChannelId" placeholder="Enter the channel id." value="">
        </div>
        <button class="btn btn-default" id="connectChannel">
          <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span> Connect Channel
        </button>
      </form>

      <video class="remote-video center-block" id="calleeRemoteVideo"></video>

    </div>
  </div>
</div>