<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h2 class="h3">Callee</h2>
      <h3 class="h4">Connect Channel</h3>
      <form class="form-inline">
          <input class="form-control" type="hidden" id="connectChannelId" value="<?= $channelId ?>">
      </form>

      <video class="remote-video center-block" id="calleeRemoteVideo"></video>

    </div>
  </div>
</div>