
<div class='aboutpage'>

	<section class="full-image-container center-text hero">
		<div class="background-color"></div>

		<div class="text-container">
		<div class="middle markdown">
			<div class="interphone">Inter<span>phone</span></div>

			<div class='body markdown--body' style='color:#FFFFFF'>스마트폰을 이용한 원격 도어록 제어 및 인터폰 구현 솔루션. 기존 서비스들과의 차별점으로 별도의 앱의 불필요함, 상대적으로 우수한 가격대비 성능비가 있다.</div>
 		</div>
		</div>
	</section>


	<section class="half-half-container left-image new-standard full-bleed">
		<div class="background-color"
			style="background-color: transparent">
		</div>
		<div class="image-half"></div>
		<div class="text-container" style="background-color: #FFFFFF;">
		</div>

		<div class="text-half" style="background-color: #FFFFFF;">
			<div class="middle">
			<div class="floater markdown">
			<div style='color:#185674'><div class='markdown--h3'>What : </br>도어록 및 인터폰 결합 솔루션</div></div>
			<div class='body markdown--body' style='color:#666666'><div><ol><li>원룸에 거주하는 학생들에게는 구매력이 부족하고 이에따라 주택 보안에 신경 쓸 여력이 부족하다.</li>
																			<li>1인 가구원의 경우 아파트처럼 경비원이 없다보니 특별한 관리인이 없는 주택 거주자로서 본인이 집에 부재 할 경우에는 택배를 받기 곤란하다. 이와 같은 문제는 집에 방문한 친구나 친지와 같은 이들에게도 적용된다.</li>
																			<li>열쇠등을 분실할 시에 이를 해결할 보조적인 방법이 필요하다.</li></ol></div></div>
			</div>
			</div>
		</div>
	</section>


	<section class="full-image-container right-text man_and_machine">
		<div class="background-color"
			style="background-image: url('https://harrysx-a.akamaihd.net/assets/images/full_images/attachments/4e6ba78e3e61a5b8a6cffc97f6bc310571597180.jpg');"></div>
	</section>


	<section class="half-half-container right-image team full-bleed">
		<div class="background-color"
			style="background-color: transparent">
		</div>
		<div class="image-half" style="background-image: url('https://harrysx-a.akamaihd.net/assets/images/half_half_images/attachments/99fc253e03c408dcfdc6606a60d231e19246f7a3.jpg'); background-color: transparent" data-bg-scale-2x="https://harrysx-a.akamaihd.net/assets/images/half_half_images/attachments/11fce0da718791b0f4890a1b5de0a6c187cfb917.jpg"></div>
		<div class="text-container" style="background-color: #FFFFFF;">
		</div>

		<div class="text-half" style="background-color: #FFFFFF;">
			<div class="middle">
			<div class="floater markdown">
			<div style='color:#185674'><div class='markdown--h3'>Why : </br>웹 어플리케이션으로 구현 해야할 사유(차별성)</div></div>
			<div class='body markdown--body' style='color:#666666'><div><ol><li>별도의 어플리케이션 설치가 필요 없다</li>
																			<li>아두이노 ESP8266 모듈을 이용한 비교적 낮은 비용</li></ol></div></div>
            </div>
			</div>
		</div>
	</section>


	<section class="full-image-container right-text blades-hands">
		<div class="background-color"
		style="background-image: url('https://harrysx-a.akamaihd.net/assets/images/full_images/attachments/4e6ba78e3e61a5b8a6cffc97f6bc310571597180.jpg');"></div>    
	</section>

	

	<section class="full-image-container center-text what-this-means">

		<div class="background-color"
			style="background-image: url('https://harrysx-a.akamaihd.net/assets/images/full_images/attachments/0c173b7f46ee7d23375c58bbdcc5ba7b16e5bc4b.jpg');"
			data-bg-scale-2x="https://harrysx-a.akamaihd.net/assets/images/full_images/attachments/0c173b7f46ee7d23375c58bbdcc5ba7b16e5bc4b.jpg"></div>
		<div class="text-container">
			<div class="middle markdown">
			<div style='color:#185674'><div class='markdown--h3'>구현에 사용된 Advanced technologies</div></div>
			<div class='body markdown--body' style='color:#666666'><div><ul><li>Web RTC : 웹 기반 P2P 통신 솔루션.</li>
																			<li>PlayRTC  : Web RTC를 보다 쉽게 사용할 수 있게 하는 Client SDK</li>
																			<li>Phalcon php : 프레임 워크</li>
																			<li>Bootstrap : css 프레임 워크</li></ul></div></div>
			</div>
		</div>
	</section>
</div>