<div class='about-container'>
	<section class='row'>
	<!-- #005876 -->
		<div class='background-color'></div>
		<div class='width-limiter'>
			<div class='col-xs-5 col-centered'>
				<h2 class="interphone">Inter<span>phone</span></h2>
				<p class='text-contents'>스마트폰을 이용한 원격 도어록 제어 및 인터폰 구현 솔루션. 기존 서비스들과의 차별점으로 별도의 앱의 불필요함, 상대적으로 우수한 가격대비 성능비가 있다.</p>
			</div>
		</div>
	</section>

	<section class='row'>
		<div class='width-limiter'>
			<div class='col-xs-6'>
				<div class='col-xs-12'>
					<img class='img-responsive' src='/img/inter.png'>
				</div>
			</div>
			<div class='col-xs-6'>
				<h2 class='reverse-color'>What : 도어록 및 인터폰 결합 솔루션</h2>
				<ol>
					<li>구매력이 부족한 학생들에게는 주택 보안에 신경 쓸 여력이 부족하다.</li>
					<li>기존 아파트와 다르게 경비원이 없는 주거환경에서는 부재 중일 경우 택배를 받기 곤란하다. 또한 집에 방문한 친구나 친지와 같은 이들에게도 적용된다.</li>
					<li>열쇠 등을 분실할 시에 이를 해결할 보조적인 방법이 필요하다.</li>
				</ol>
			</div>
		</div>
	</section>

	<section class='row'>
		<div class='background-color'></div>
		<div class='width-limiter'>
			<div class='col-xs-6'>
				<h2 class='title-color'>Why : 웹 어플리케이션으로 구현 해야할 사유</h2>
				<ol>
					<li>실버타운에서 개발한 interphone은 별도의 어플리케이션 설치가 필요 없다.</li>
					<li>아두이노 ESP8266 모듈을 이용하여 낮은 비용으로 사용 가능.</li>
					<li>어플리케이션에 익숙치 않은 장년층을 대상으로 주소 하나만 알고 있다면 손 쉽게 이용 가능.</li>
				</ol>
			</div>
			<div class='col-xs-6'>
				<div class='col-xs-12'>
					<img class='img-responsive' src='/img/background1.jpg'>
				</div>
			</div>
		</div>
	</section>

	<section class='row'>
		<div class='width-limiter'>
			<div class='col-xs-6 col-centered'>
				<h2 class='reverse-color'>구현에 사용된 Advanced technologies</h2>
				<ul>
					<li>Web RTC : 웹 기반 P2P 통신 솔루션</li>
					<li>PlayRTC : Web RTC를 보다 쉽게 사용할 수 있게 하는 Client SDK</li>
					<li>Phalcon php : 프레임 워크</li>
					<li>Bootstrap : css 프레임 워크</li>
				</ul>
			</div>
		</div>
	</section>
</div>