<form class="form-register" method="post" action="/user/register">

    <div class="form-register-with-email">

        <div class="form-white-background">

            <div class="form-title-row">
                <h1>회원가입</h1>
            </div>

            <div class="form-row">
                <label>
                    <span>이메일</span>
                    <input type="email" name="email">
                </label>
            </div>

            <div class="form-row">
                <label>
                    <span>비밀번호</span>
                    <input type="password" name="password">
                </label>
            </div>

            <div class="form-row">
                <label>
                    <span>핸드폰 번호</span>
                    <input type="text" name="phone">
                </label>
            </div>

            <div class="form-row">
                <button type="submit">Register</button>
            </div>

            <a href="/login" class="form-log-in-with-existing">이미 계정이 있으세요?</a>

        </div>


    </div>

</form>