
  <form class="form-inline" action="/user/register" method="post">
  <div class="form-group">
    <label for="userId">email</label>
    <input type="text" name='email' class="form-control" id="userId" placeholder="이메일을 입력해주세요" value="">
  </div>
  <div class="form-group">
    <label for="phone">phone:</label>
    <input type="tel" name='phone' class="form-control" id="phone" placeholder="Enter phone number">
  </div>
  <div class="form-group">
    <label for="pwd">Password:</label>
    <input type="password" name='password' class="form-control" id="pwd" placeholder="Enter password">
  </div>
  <div class="checkbox">
    <label><input type="checkbox"> Remember me</label>
  </div>
  <button type="submit" class="btn btn-default" id="IdPwdSubmit">Submit</button>
</form>