<div class="container">
  <div class="row">

    <div class="col-md-12">
      <h1 class="page-header" id="userStat">Visitor</h1>
    </div>

    <div class="col-md-6 col-md-offset-3 hide">
      <div class="alert alert-info alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2">

      <input type='hidden' id='userId' value='testingIDValue'>
      <input type="hidden" id='securityToken' name="<?= $this->security->getTokenKey() ?>"
        value="<?= $this->security->getToken() ?>"/>

      <button class="btn btn-default btn-sm btn-block" id="disconnectChannel">
        <span class="glyphicon glyphicon-stop" aria-hidden="true"></span> Disconnect
      </button>
     </div>
     <div class="col-md-10">
      <div id="loading-container" class='col-md-12'>
        <div class="stick"></div>
        <div class="stick"></div>
        <div class="stick"></div>
        <div class="stick"></div>
        <div class="stick"></div>
        <div class="stick"></div>
        
        <p id='loading-text'>연결중입니다...</p>
      </div>
      <audio id="callerRemoteVideo"></audio>
     </div>
  </div>
</div>