<div class="container">
  <div class="row">

    <div class="col-md-12">
      <h1 class="page-header" id="userStat">Guest</h1>
    </div>

    <div class="col-md-6 col-md-offset-3 hide">
      <div class="alert alert-info alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">

      <input type='hidden' id='userId' value='testingIDValue'>
      <input type="hidden" id='securityToken' name="<?= $this->security->getTokenKey() ?>"
        value="<?= $this->security->getToken() ?>"/>

      <h2 class="h3">Channel</h2>
      <button class="btn btn-default btn-sm btn-block" id="disconnectChannel">
        <span class="glyphicon glyphicon-stop" aria-hidden="true"></span> Disconnect
      </button>

       <h3 class="h4 Connecth3">Connect</h3>
       <button class="btn btn-default btn-sm" id="refreshChannel">
        <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span> Refresh
      </button>
       <div class="list-group channel-list" id="channelList"></div>
     </div>

      <div class="chat-timeline" id="timeline"></div>

      <form>
        <label class="sr-only" for="sendMessage">Transfer Message</label>
        <div class="input-group input-group-sm">
          <div class="input-group-addon">
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          </div>
          <input type="text" class="form-control" id="sendMessage" placeholder="Enter your message.">
          <span class="input-group-btn">
            <button class="btn btn-default" id="sendText">
              <span class="glyphicon glyphicon-send" aria-hidden="true"></span> Send
            </button>
          </span>
        </div>
      </form>

      <div class="col-md-7 videoArea">
        <h2 class="h3">Remote</h2>
        <div class="well">
          <video class="remote-video center-block" id="remoteVideo"></video>
        </div>
      </div>

      <div class="col-md-3 videoArea">
        <h2 class="h3">Local</h2>
        <div class="well">
          <video class="local-video center-block" id="localVideo" muted></video>
        </div>
      </div>

  </div>
</div>