<!-- 검색 기능을 표시할 <div>를 생성한다 -->

<div class='width-limiter'>
  <form action='/visitor' class='form-searching-host' method='post'>
    <div id="postcodify"></div>
    <div class="form-row">
        <label>
            <input type="text" name="address" id="address" value="" readonly/>
        </label>
    </div>
    <input type='submit' value='연결하기'>
  </form>
</div>

<!-- 위에서 생성한 <div>에 검색 기능을 표시하고, 결과를 입력할 <input>들과 연동한다 -->
<script>
    $(function() { $("#postcodify").postcodify({
        insertPostcode5 : "#postcode",
        insertAddress : "#address",
        insertDetails : "#details",
        insertExtraInfo : "#extra_info",
        hideOldAddresses : false
    }); });
</script>