 <!DOCTYPE html>
 
<html lang="en">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="description" content="web-rtc interphone">
		<meta name="author" content="">
		<!-- <link rel="icon" href="http://v4-alpha.getbootstrap.com/favicon.ico"> -->

		<title>인터폰 :)</title>

		<!-- Bootstrap core CSS -->
		<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">

		<?php $this->assets->outputCss(); ?>
		<?php $this->assets->outputCss("header"); ?>
		<?php $this->assets->outputCss("footer"); ?>

		<script src="http://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
		<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

		<?php $this->assets->outputJs(); ?>
	</head>

	<body>
        <?php echo $this->getContent(); ?>
    </body>
</html>