
<form class="form-inline" action="/user/login" method="post">
    <div class="form-group">
        <label for="userId">User Id</label>
        <input type="text" class="form-control" id="userId" placeholder="Enter your user email." value="">
    </div>
    <div class="form-group">
        <label for="pwd">Password:</label>
        <input type="password" class="form-control" id="pwd" placeholder="Enter password">
    </div>
        <div class="checkbox">
        <label><input type="checkbox"> Remember me</label>
    </div>
    <button type="submit" class="btn btn-default" id="IdPwdSubmit">Submit</button>
</form>